# -*- coding: utf-8 -*-
"""atvdmario.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RCkBqDqPfmKJUnXrFs9xA5CfeSDN0NaH
"""

import requests

from bs4 import BeautifulSoup

from tabulate import tabulate

from prettytable import PrettyTable

url = 'https://www.santosfc.com.br/artigos/'

response = requests.get(url)

response.status_code

sp = BeautifulSoup(response.text, 'html.parser')

head = sp.find(class_='elementor-heading-title elementor-size-default').text
head

def extrair_links_titulos(html_elements):
    links = []
    titulos = []
    for element in html_elements:
        link = element.find('a')['href']
        titulo = element.find('a').text
        links.append(link)
        titulos.append(titulo)
    return links, titulos

def extrair_links(html_elements):
    links = []
    for element in html_elements:
        link = element.find('a')['href']
        links.append(link)
    return links

def extrair_titulos(html_elements):
    titulos = []
    for element in html_elements:
        titulo = element.find('a').text
        titulos.append(titulo)
    return titulos

links, titulos = extrair_links_titulos(titulos)
print("Links:", links)
print("Títulos:", titulos)

datas = sp.find_all(class_='meta-item')
for data in datas:
    print(data.text)

def extrair_links_titulos(html_elements):
    links = []
    titulos = []
    for element in html_elements:
        link = element.find('a')['href']
        titulo = element.find('a').text
        links.append(link)
        titulos.append(titulo)
    return links, titulos

titulos = sp.find_all(class_='wke-post-title')
links, titulos = extrair_links_titulos(titulos)

datas = sp.find_all(class_='meta-item')
datas_text = [data.text for data in datas]

html_table = "<table border='1'><tr><th>Título</th><th>Data</th><th>Link</th></tr>"
for titulo, data, link in zip(titulos, datas_text, links):
    html_table += f"<tr><td>{titulo}</td><td>{data}</td><td><a href='{link}'>Link</a></td></tr>"
html_table += "</table>"

print(html_table)